export const REQUESTED_POSTS = 'REQUESTED_POSTS';
export const CREATED_POST = 'CREATED_POST';
export const FETCHED_POST = 'FETCHED_POST';
export const RECIEVED_POSTS = 'RECIEVED_POSTS';
export const RECIEVED_POST = 'RECIEVED_POST';
export const DELETED_POST = 'DELETED_POST';
export const DELETED = 'DELETED';
